config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  resources :theaters, only: :index
  resources :products do
    resources :reviews, only: [:new, :create, :edit, :destroy, :update]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product, counter_cache: :likes_count
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def review_average
    reviews.average(:rate).round
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/scraping.rb
class Scraping
  def self.movie_total
    links = []
    agent = Mechanize.new
    agent.user_agent_alias = 'Windows Mozilla'
    movie_urls("https://filmarks.com/list/genre/20")
    # current_page = agent.get('https://filmarks.com/list/genre')
    # elements = current_page.search('.c-list-line__item--has-bar a')
    # elements.each do |ele|
    #  links << ele.get_attribute('href')
    # end

    # links.each do |link|
    #   movie_urls('https://filmarks.com' + link)
    # end
  end


  def self.movie_urls(link)
    links = []
    agent = Mechanize.new
    agent.user_agent_alias = 'Windows Mozilla'
    # agent.user_agent_alias = 'Windows Chrome'
    next_url = ""

    while true
      # p next_url
      current_page = agent.get(link + next_url)
      elements = current_page.search('.p-movie-cassette__people__readmore .p-movie-cassette__readmore')
      elements.each do |ele|
        links << ele.get_attribute('href')
      end
      # p links

      next_link = current_page.at('a.c-pagination__next')
      break unless next_link
      next_url = next_link.get_attribute('href')
      idx = next_url.index("?")
      next_url = next_url[idx..-1]
    end

    links.each do |link|
    
      get_product('https://filmarks.com' + link)
    end
  end
    
   def self.get_product(link)
    agent = Mechanize.new
    agent.user_agent_alias = 'Windows Mozilla'
    page = agent.get(link)
    title = page.search('.p-content-detail__title span').inner_text if page.search('.p-content-detail__title span')
    image_url = page.at('.c-content__jacket img')[:src] if page.at('.c-content__jacket img')
    open_date = page.at('.p-content-detail__other-info-title').inner_text.match(/\d+年\d+月\d+日/) if page.at('.p-content-detail__other-info-title')
    director = page.at('.c-label').inner_text if page.at('.c-label')
    # detail = page.at("#js-content-detail-synopsis").inner_text
    product = Product.where(title: title).first_or_initialize
    product.title = title
    product.image_url = image_url
    product.open_date = open_date
    product.director = director

    # product.save
    puts title
    
    puts image_url
    # product.save
    # puts detail
    # puts title
    # puts image_url
     puts open_date
     puts director
   end
end

app/models/selenium.rb
# require 'selenium-webdriver'
# driver = Selenium::WebDriver.for :chrome
# wait = Selenium::WebDriver::Wait.new(timeout: 80)
# driver.navigate.to 'https://filmarks.com/list/genre/8'
  
# # driver.find_elements(:xpath, '//img')
# element=driver.find_element(:xpath, '/html/body/div[4]/div[2]/div[2]/div[1]/div[3]/div[1]/div[2]/div[6]/a')
#   detail = driver.find_element(:xpath, '//*[@id="js-content-detail-synopsis"]/div/div/button').click
#   more_detail = driver.find_element(:id, 'js-content-detail-synopsis').text
#  puts more_detail


# detail = driver.find_elements(:class,'p-content-detail__synopsis-desc is-show-all')
# elements.each do |element|
#   puts element.text
# end
# puts element
# puts detail
# puts detail

app/models/theater.rb
class Theater < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews

  has_one_attached :avatar
  has_many :likes
  has_many :products, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, product_id: params[:product_id])
    @like.reload
    @likes = Like.where(product_id: params[:product_id])
    @products = Product.all
    @product = Product.find(params[:product_id])
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, product_id: params[:product_id])
    @like.destroy
    @likes = Like.where(product_id: params[:product_id])
    @products = Product.all
    @product = Product.find(params[:product_id])
    
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 
  def index
    @products = Product.order('id ASC').page(params[:page]).per(18)
    product_ids = Review.group(:product_id).order('count_product_id DESC').limit(5).count(:product_id).keys
    @ranking = product_ids.map { |id| Product.find(id) }
    @product = Product.new
    @review = Review.new
    # @res = Amazon::Ecs.item_search("検索したいキーワード",
    #   :search_index   => 'Books',
    #   :response_group => 'Medium',
    #   :country        => 'jp'
    # )
  end

  
  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def search
    @products = Product.where('title LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  private
  def create_params
    params.require(:review).permit(:rate, :review).merge(user_id: current_user.id, product_id: params[:product_id])
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  before_action :ranking
  def ranking
    product_ids = Review.group(:product_id).order('count_product_id DESC').limit(5).count(:product_id).keys
    @ranking = product_ids.map { |id| Product.find(id) }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 def new
  # @user = User.find(3)
  @product = Product.find(params[:product_id])
  @review = Review.new
 end

 def create
  Review.create(create_params)
  redirect_to controller: :products, action: :index
 end

 def destroy
  review = Review.find(params[:id])
  @review=review.destroy if review.user.nickname == current_user.nickname
  redirect_to controller: :products, action: :index
 end

#  def edit
#   @review = Review.find(params[:id])
#  end

#  def update
#   review = Review.find(params[:id])
#   if review.user.nickname == current_user.nickname
#     review.update(create_params)
#   end
# end

 private
  def create_params
    params.require(:review).permit(:rate, :review).merge(user_id: current_user.id, product_id: params[:product_id])
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def search
    latitude = params[:latitude]
    longitude = params[:longitude]
  
    @places = Theater.all.within(10, origin: [latitude, longitude])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if product.like_user(current_user.id) %>
    <%= button_to product_like_path(product.id, Like.find_by(product_id: product.id, user_id: current_user.id)), method: :delete, id: "product-#{product.id}", remote: true do %>
      <i class="fa fa-plus-square "></i> 
      <span>
        <%= product.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to product_likes_path(product.id), id: "product-#{product.id}", method: :post, remote: true do %>
      <i class="fa fa-plus-square"></i>
      <span>
        <%= product.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <i class="fa fa-plus-square"></i>
    <span>
      <%= product.likes_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
var par = $("#product-<%= @product.id %>").parent();
par.attr('action', "<%= product_like_path(@product.id, @like.id) %>");
$('form').on('submit', function(e) {
    e.preventDefault();
  });
par.html("<%= j(render partial: 'likes/like', locals: { product: @product, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
var par = $("#product-<%= @product.id %>").parent();
par.attr('action', "<%= product_likes_path(@product.id) %>");
par.attr('method', 'POST');
par.html("<%= j(render partial: 'likes/like', locals: { product: @product, likes: @likes, like: @like }) %>");

app/views/products/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron" style="background:#ffe100;">
  <div class="container">
    <h4 class="text-small hr-bottom--thin no-space-bottom">
      <i class="icon-crown color-gray-light">Ranking</i>
    </h4>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="min-width:200px; width:25%; margin:0 auto">
      <div class="carousel-inner">
      <% @ranking.each_with_index do |product, i| %>
        <% if i == 1 %>
          <div class="carousel-item active">
            <img class="d-block w-100" src="<%=product.image_url%>" alt="<%=product.title%>">
          </div>
        <% else %>
          <div class="carousel-item">
            <img class="d-block w-100" src="<%=product.image_url%>" alt="<%=product.title%>">
          </div>
        <% end %>
      <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 w-75">
        <div class="card mb-4">
          <img src="<%=product.image_url%>" class="img-responsive">
          <div class="card-body">
            <h5 class="mb-0"><%=product.title%></h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <div class="d-flex justify-content-between align-items-center">
            
              <div class="btn-group">
              <%if user_signed_in?%>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                <a class="icon fa-eye" href="/products/<%= product.id %>"></a></button>
                <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#Modal<%= product.id %>"><i class="fa fa-paint-brush fa-lg"></i></button>
              <%end%>
                <%= form_for @review,url:product_reviews_path(product.id) do |f| %>
                  <div class="modal fade" id="Modal<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                      <div class="modal-dialog">
                          <div class="modal-content">
                              <div class="modal-header" style="background-color:yellow;">
                                <h4>Review</h4>    
                              </div>
                              <div class="modal-header" style="background-color:#555;">
                                <div style="margin: 8px 0">
                                  <%= f.label :rate, 'score', style: { 'margin-right' => 8 } %>
                                  <div class="range">
                                    <%= f.range_field :rate, max: "5",min: "1", step: "0.1", value: "3" %>
                                    <span id="value">3</span>
                                  </div>
                                </div>
                              </div>
                              <div class="modal-body">
                                <div style="margin: 8px 0">
                                  <%= f.text_area :review, placeholder: 'レビュー無記名でも投稿できます', style: 'width: 100%;height: 300px;' %>
                                </div>      
                              </div>
                              <div class="modal-footer">
                                  <%= button_tag type: "submit", class: "btn btn--block" do %>
                                      投稿する<i class="icon-arrow-right"></i>
                                      <% end %>
                                  <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                              </div>
                          </div>
                      </div>
                  </div>
                <% end %>
                <div class="btn btn-sm btn-outline-secondary">
                <%= render partial: "likes/like", locals: { product: product } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<hr>
</div> <!-- /container -->

    
<div class="kaminari" style="margin 0 auto">
  <%= paginate(@products) %>
</div>



<footer class="container">
<p>© SasanoCompany 2019/07/20</p>
</footer>

<script>
  var elem = document.getElementsByClassName('range');
  var rangeValue = function (elem, target) {
    return function(evt){
      target.innerHTML = elem.value;
    }
  }
  for(var i = 0, max = elem.length; i < max; i++){
    bar = elem[i].getElementsByTagName('input')[0];
    target = elem[i].getElementsByTagName('span')[0];
    bar.addEventListener('input', rangeValue(bar, target));
  }
</script>

app/views/products/search.html.erb
<%@products.each do |product|%>

<div class="search_view">
  <div class="col-md-4" style="margin: 0 auto; ">
    <div class="card mb-4 shadow-sm">
      <img src="<%=product.image_url%>" class="img-responsive">
      <div class="card-body">
        <h5 class="mb-0"><%=product.title%></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <a href="/products/<%= product.id %>"><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/products/show.html.erb
<div class="col-md-10">
  <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col-auto d-none d-lg-block">
     <img src="<%= @product.image_url %>" alt="<%= @product.title %>">
    </div>
    <div class="col p-4 d-flex flex-column position-static">
      <h4 strong class="d-inline-block mb-2 text-primary">Title</h4>
      <h4 class="mb-0"><%=@product.title%></h3>
      <div class="mb-1 text-muted"><%=@product.open_date%></div>
      <p class="card-text mb-auto">
        第二次世界大戦時、ドイツ軍が誇った世界最強の暗号＜エニグマ＞。
        世界の運命は、解読不可能と言われた暗号解読に挑んだ、一人の天才数学者アラン・チューリングに託された。
        英国政府が50年間隠し続けた、一人の天才の真実の物語。時代に翻弄された男の秘密と数奇な人生とは――？!
      </p>
      
      <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#Modal<%=@product.id %>"><i class="fa fa-paint-brush fa-lg"></i></button>
    </div>
  </div>

 <%= form_for @review,url:product_reviews_path(@product.id) do |f| %>
  <div class="modal fade" id="Modal<%=@product.id %>" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header" style="background-color:yellow;">
                <h4>Review</h4>    
              </div>
              <div class="modal-header" style="background-color:#555;">
                <div style="margin: 8px 0">
                  <%= f.label :rate, 'スコア', style: { 'margin-right' => 8 } %>
                  <div class="range">
                    <%= f.range_field :rate, max: "5",min: "1", step: "0.1", value: "3" %>
                    <span id="value">3</span>
                  </div>
                </div>
              </div>
              <div class="modal-body">
                <div style="margin: 8px 0">
                  <%= f.text_area :review, placeholder: 'レビュー無記名でも投稿できます', style: 'width: 100%;height: 300px;' %>
                </div>      
              </div>
              <div class="modal-footer">
                  <%= button_tag type: "submit", class: "btn btn--block" do %>
                      投稿する<i class="icon-arrow-right"></i>
                      <% end %>
                  <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
              </div>
          </div>
      </div>
  </div>
<% end %>

<script>
  var elem = document.getElementsByClassName('range');
  var rangeValue = function (elem, target) {
    return function(evt){
      target.innerHTML = elem.value;
    }
  }
  for(var i = 0, max = elem.length; i < max; i++){
    bar = elem[i].getElementsByTagName('input')[0];
    target = elem[i].getElementsByTagName('span')[0];
    bar.addEventListener('input', rangeValue(bar, target));
  }
</script>



  
  <% @product.reviews.each do |review| %>
    <div class="card" style="width: 30rem; margin:0 auto; margin-bottom:20px; background-color:#343a40!important;">
     <p style="font-size:20px; color:white; padding-left:20px;"><%=review.user.nickname%></p>
      <div class="card-body" style="margin-top:0;">
        <h5 class="card-title">Rate: <%=review.rate%></h5>
        <p class="card-text">Review:<%=review.review%></p>
        <button type="button" class="btn btn-sm btn-outline-secondary"><i class="fa fa-thumbs-up "><a href="#" class="card-link"></a></i></button>
        <%= link_to "/products/#{review.product.id}/reviews/#{review.id}", method: :delete,class: "delete",data: { confirm: '削除しますか？' } do%>
          <i class="fa fa-trash"></i> 
        <%# <%= link_to '編集', "/products/#{review.product.id}/reviews/#{review.id}/edit", method: :get %> 
        <% end %>
      </div>
    </div>
  <%end%>

  
</div>

app/views/theaters/index.html.erb
<div class="currentLocation">
  <button type="button" class="btn btn-sm btn-outline-secondary">現在地から探す</button>
</div>

<script>
class @CurrentLocations
  @getCurrentLocation: 
    $('.currentLocation').on 'click', 
      if navigator.geolocation
        navigator.geolocation.getCurrentPosition(successGetPosition, failGetPosition, options)
      else
        message = 'ご使用中のブラウザは現在地検索に対応されておりません。'
        Alert.set('warning', message)

  successGetPosition = (position) 
    window.location.href = "/shops/searches?latitude=#{position.coords.latitude}&longitude=#{position.coords.longitude}"

  options =
    enableHighAccuracy: true

  failGetPosition = (error) 
    switch error.code
      when 1
        message = '位置情報の提供を許可してください。'
      when 2
        message = '位置情報の取得に失敗しました。'
    Alert.set('warning', message)
</script>






  <div class="Look">
    <p>近くの映画館を探す</p>
  </div>

  <div class="tag">
    <form onsubmit="return false;"> 
        <input type="text" value="三宮駅" id="address" placeholder="施設名"> 
        <button type="button" value="検索" id="map_button">検索</button>
    </form>
  </div>

  <div class="post">
   <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <form class="h-adr">
    <span class="p-country-name" style="display:none;">Japan</span>
    〒<input type="text" class="p-postal-code" size="8" maxlength="8"><br>
    <input type="text" class="p-region p-locality p-street-address p-extended-address">
    </form>
  </div>
  

<div id="map" style="margin:0 auto; margin-top:20px;"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 35.658034 , lng: 139.701636},
          zoom: 8
        });
      }
    </script>

<div class ="location">
  <p hidden>緯度・経度を表示する<br>
     緯度 <input type="text" id="lat" value=""><br>
     経度 <input type="text" id="lng" value=""><br>
     地図上をクリックしてね!!</p>
</div>


<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY']%>"></script>

<script>


 var getMap = (function() {
  function codeAddress(address) {
   
    var geocoder = new google.maps.Geocoder();
 
   
    var mapOptions = {
      zoom: 16,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
 
    var map = new google.maps.Map(document.getElementById("map"), mapOptions);
 
    var marker;
     
   
    geocoder.geocode( { 'address': address}, function(results, status) {
       

      if (status == google.maps.GeocoderStatus.OK) {
         
       
        map.setCenter(results[0].geometry.location);
         
       
        document.getElementById('lat').value=results[0].geometry.location.lat();
        document.getElementById('lng').value=results[0].geometry.location.lng();
         
      
        marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
        });
       
      
      } else {
        console.log('Geocode was not successful for the following reason: ' + status);
      }
     
    });
 
    map.addListener('click', function(e) {
      getClickLatLng(e.latLng, map);
    });
    function getClickLatLng(lat_lng, map) {
       

      document.getElementById('lat').value=lat_lng.lat();
      document.getElementById('lng').value=lat_lng.lng();
         

      marker.setMap(null);
      marker = new google.maps.Marker({
        position: lat_lng,
        map: map
      });
     
      
      map.panTo(lat_lng);
    }
   
  }
   
 
  return {
    getAddress: function() {
   
      var button = document.getElementById("map_button");
       
   
      button.onclick = function() {
      
        var address = document.getElementById("address").value;
      
        codeAddress(address);
      }
       
     
      window.onload = function(){
      
        var address = document.getElementById("address").value;
        
        codeAddress(address);
      }
    }
   
  };
 
})();
getMap.getAddress();


</script>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-6">
            <div class="card hovercard">
                <div class="cardheader">
                </div>
                <div class="avatar">
                    <img alt="" src="">
                </div>
                <div class="info">
                    <div class="title">
                        <div class="user_image"><%= image_tag  current_user.avatar, class: "avatar" %></div>
                    </div>
                    <div class="desc">Passionate designer</div>
                    <div class="desc">Curious developer</div>
                    <div class="desc">Tech geek</div>
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/BxIxPgNGz8EyoL7">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://plus.google.com/+ahmshahnuralam">
                      <i class="fas fa-envelope"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-facebook"></i>
                    </a>
                </div>
            </div>
        </div>
	</div>
</div>